version: 0.2

phases:
  install:
    commands:
      - apt-get update --fix-missing
      - apt-get -yq upgrade
  # Install Apache2
      - echo "---------------Installing Apache2--------------------"
      - apt-get install -yq apache2
      - systemctl is-active apache2
      - systemctl is-enabled apache2
  #Install php 
      - echo "--------------- Intalling php ------------------------"
      - apt-get -yq install php7.2
      - apt-get install -yq php7.2-cli php7.2-fpm php7.2-soap php7.2-json php7.2-dom php7.2-pdo php7.2-zip
      - apt-get install -yq php7.2-mysqli php7.2-gd php7.2-gettext php7.2-xmlreader php7.2-xmlrpc php7.2-iconv         php7.2-curl \
      - apt-get install -yq php7.2-ctype php7.2-mbstring
    # criando o virtual hostname
      - echo "--------------- Creating Virtual Host -----------------"
      - touch /etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "127.0.0.1 teste-smarkio.com.br www.teste-smarkio.com.br" >> /etc/hosts
      - echo "<VirtualHost *:80>" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "        ServerName teste-smarkio.com.br" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "        ServerAlias www.teste-smarkio.com.br" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "        DocumentRoot /home/junior/Documentos/Projeto-smarkio" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "        SetEnv CI_ENV development" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "">>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "        <Directory /home/junior/Documentos/Projeto-smarkio>" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "                AllowOverride All" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "                Allow from All" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf\
      - echo "                Require all granted\n" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "        </Directory>" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "">>/etc/apache2/sites-available/teste-smarkio.com.br.conf\
      - echo "        ErrorLog /var/log/apache2/error_log" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "        CustomLog /var/log/apache2/access_log common" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - echo "</VirtualHost>" >>/etc/apache2/sites-available/teste-smarkio.com.br.conf
      - a2ensite teste-smarkio.com.br.conf
      - a2enmod rewrite
      - service apache2 reload
  pre_build:
    commands:
    - echo Entering pre_build phase...
    - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - php echo "Im working";
  
  post_build:
    command:
      - php echo " Pos-build";