version: 0.2

phases:
  install:
    commands:
      - apt-get update --fix-missing
      - apt-get -yq upgrade
      - apt-get -yq  install --reinstall systemd 
  
  #Install php 
      - echo "--------------- Intalling php ------------------------"
      - apt-get -yq install php7.2
      - apt-get install -yq php7.2-cli php7.2-fpm php7.2-soap php7.2-json php7.2-dom php7.2-pdo php7.2-zip
      - apt-get install -yq php7.2-mysqli php7.2-gd php7.2-gettext php7.2-xmlreader php7.2-xmlrpc php7.2-iconv         php7.2-curl \
      - apt-get install -yq php7.2-ctype php7.2-mbstring
    
  pre_build:
    commands:
    - echo Entering pre_build phase...
    - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Im working
  post_build:
    command:
      - echo Pos-build